version: '3'
#https://alexgallacher.com/how-to-setup-ghost-with-nginx-and-lets-encrypt/

services:
  blog:
    image: ghost:${GHOST_VERSION}
    container_name: blog
    restart: unless-stopped
    expose:
      - 2368
    env_file:
      - .env
    volumes:
      - ${GHOST_DATA}:/var/lib/ghost/content
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
